# Generated by Django 4.0.4 on 2022-04-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=250), max_length=255, unique=True),
        ),
    ]
