# Generated by Django 4.0.3 on 2022-03-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='image',
            field=models.ImageField(default='images/profile-photo.png', upload_to='images/'),
        ),
    ]
