# Generated by Django 4.0.3 on 2022-03-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_homepage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='image',
            field=models.ImageField(default='images/Profile-Photo.png', upload_to='images/'),
        ),
    ]
