# Generated by Django 4.0.3 on 2022-03-29 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_homepage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='btntext',
        ),
    ]
